### ISSUE TITLE
TypeError: Cannot read property 'getTile' of undefined

### ISSUE THREAD

**Issue by jvaldezch** [naturalatlas/tilestrata#26]
Hi, I'm trying to pass the layer name dynamically but when trying to run I'm getting an error "TypeError: Cannot read property 'getTile' of undefined". 

```
const express = require('express');
const fs = require('fs');

const app = express();

app.get('/', function (req, res, next) {
    res.send('Hello World!');
});

app.get('/tileserver/:layer/:z/:x/:y/tile.png', function (req, res, next) {
    const layer = req.params.layer;
    const x = req.params.x;
    const y = req.params.y;
    const z = req.params.z;
    
    const mapfile = __dirname + '/maps/' + layer + '.xml';
    const dircache = '../cache/' + layer;
    
    fs.exists(mapfile, function(exists) {
        if (exists) {

            var tilestrata = require('tilestrata');
            var disk = require('tilestrata-disk');
            var sharp = require('tilestrata-sharp');
            var mapnik = require('tilestrata-mapnik');
            var dependency = require('tilestrata-dependency');

            var strata = tilestrata();

            strata.layer('basemap')
                .route('tile@2x.png')
                    .use(disk.cache({dir: dircache}))
                    .use(mapnik({
                        pathname: mapfile,
                        tileSize: 512,
                        layer: 'all',
                        scale: 2
                    }))
                .route('tile.png')
                    .use(disk.cache({dir: dircache}))
                    .use(dependency('basemap', 'tile@2x.png'))
                    .use(sharp(function(image, sharp) {
                        return image.resize(256);
                    }));
            strata.listen();

            strata.getTile('basemap', 'tile.png', x, y, z, function(err, img, hdr) {
                if (err) {
                    console.log(err);
                    res.statusCode = 401;
                    res.send('None shall pass');
                } else {
                    res.writeHead(200, {
                        'Content-Type': 'image/png',
                        'Content-Length': img.length
                    });
                    res.end(img); 
                }
            });

        } else {
            res.statusCode = 401;
            res.send("Mapfile dont exists");
        }
    });
    
});

app.use(function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
});

app.listen(3000);
```

**Comment by jvaldezch** [comment]
@brandonreavis 
```
/home/jvaldez/Repositories/tile_server/node_modules/tilestrata-mapnik/index.js:50
		source.getTile(req.z, req.x, req.y, function(err, buffer, headers) {
		       ^

TypeError: Cannot read property 'getTile' of undefined
    at Object.serveImage [as serve] (/home/jvaldez/Repositories/tile_server/node_modules/tilestrata-mapnik/index.js:50:10)
    at step_runProvider (/home/jvaldez/Repositories/tile_server/node_modules/tilestrata/lib/TileRequestHandler.js:222:25)
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:689:13
    at iterate (/home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:265:13)
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:277:29
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:44:16
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:694:17
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:173:37
    at complete (/home/jvaldez/Repositories/tile_server/node_modules/tilestrata/lib/TileRequestHandler.js:207:6)
    at /home/jvaldez/Repositories/tile_server/node_modules/tilestrata/node_modules/async/lib/async.js:52:16
[nodemon] app crashed - waiting for file changes before starting...

```

**Comment by jvaldezch** [comment]
@brandonreavis thanks for the advice I will try both approaches then.

**Comment by yh371174229** [comment]
> @brandonreavis thanks for the advice I will try both approaches then.
Do you solve it ?? I meet this error too.
https://github.com/naturalatlas/tilestrata-mapnik/issues/9
