### ISSUE TITLE
Error using the middleware

### ISSUE THREAD

**Issue by Zn4rK** [naturalatlas/tilestrata#5]
This is the error I get:
```
[project-path]/node_modules/tilestrata-mapnik/index.js:49
		source.getTile(req.z, req.x, req.y, function(err, buffer, headers) {
		       ^
TypeError: Cannot call method 'getTile' of undefined
    at Object.serveImage [as serve] ([project-path]/node_modules/tilestrata-mapnik/index.js:49:10)
    at step_runProvider ([project-path]/node_modules/tilestrata/lib/TileRequestHandler.js:187:18)
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:607:21
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:246:17
    at iterate ([project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:146:13)
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:157:25
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:248:21
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:612:34
    at complete ([project-path]/node_modules/tilestrata/lib/TileRequestHandler.js:173:6)
    at [project-path]/node_modules/tilestrata/node_modules/async/lib/async.js:154:25
    at [project-path]/node_modules/tilestrata/lib/TileRequestHandler.js:162:11
    at [project-path]/node_modules/tilestrata-disk/index.js:35:19
    at fs.js:207:20
    at OpenReq.Req.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:135:5)
    at OpenReq.done (/usr/lib/nodejs/graceful-fs/graceful-fs.js:64:22)
    at Object.oncomplete (fs.js:107:15)
```
I'm using express.js 4.13.1, tilestrata 1.4.0 and tilestrata-mapnik 0.2.3.

I'm more or less using the examples from the readme.md on tilestrata.

I haven't had a chance to examine this myself just yet, but if I remove the use of the middleware and just use strata.listen(), it works just fine.

**Comment by brianreavis** [comment]
Ah! The normal `listen()` method handles initializing all the plugins, and the middleware doesn't. That's a bug I'll try to patch up tonight. The solution involves initializing on the `middleware()` call, making sure to wait for it to complete before letting any of the requests through.

**Comment by brianreavis** [comment]
[1.4.1](https://github.com/naturalatlas/tilestrata/releases/tag/v1.4.1) is out now (should fix the problem)
